### ISSUE TITLE
Cannot read property of 'ioc' of null

### ISSUE THREAD

**Issue by jpcbarros** [enniel/adonis-lucid-polymorphic#4]
Getting this error just after adding `adonis-lucid-polymorphic/providers/PolymorphicProvider` to the app providers.

Debug:
`warning:
  WARNING: Adonis has detected an unhandled promise rejection, which may
  cause undesired behavior in production.
  To stop this warning, use catch() on promises or wrap await
  calls inside try/catch.

TypeError: Cannot read property 'ioc' of null
    at IocResolver.get ioc [as ioc] (/app/node_modules/@adonisjs/lucid/lib/iocResolver.js:58:23)
    at Object.<anonymous> (/app/node_modules/adonis-lucid-polymorphic/src/Traits/Morphable.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at PolymorphicProvider.register (/app/node_modules/adonis-lucid-polymorphic/providers/PolymorphicProvider.js:7:23)`

**Comment by enniel** [comment]
@jpcbarros You are added `LucidProvider` to providers? What version of @adonisjs/lucid are you using?

**Comment by enniel** [comment]
@jpcbarros This bug fixed in version 1.0.1

**Comment by jpcbarros** [comment]
Hey @enniel,

Yes, LucidProvider is added tho the providers and I'm using Adonis v4.1.0 and Adonis/Lucid v6.1.3. I wasn't yet able to test the fix because its not published on NPM yet, right?

**Comment by enniel** [comment]
@jpcbarros Sorry for this. You can test it now!

**Comment by jpcbarros** [comment]
Hey @enniel , seems to be fixed :) tkss
